# Generated by Django 4.2.1 on 2023-05-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField()),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('usd', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=200)),
                ('job_link', models.CharField(max_length=250)),
                ('salary_min_usd', models.IntegerField()),
                ('salary_max_usd', models.IntegerField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('published', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.location')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.companies')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.currencies')),
                ('desc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.descriptions')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.resource')),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.location'),
        ),
    ]
