# Generated by Django 4.2.1 on 2023-05-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='desc_id',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='resource_id',
            new_name='resource',
        ),
    ]
