# Generated by Django 4.2.1 on 2023-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0002_rename_city_id_companies_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='salary_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_max_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_min_usd',
            field=models.IntegerField(null=True),
        ),
    ]
