# Generated by Django 4.2.1 on 2023-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0004_alter_vacancies_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
