# Generated by Django 4.2.1 on 2023-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableAutomobiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Color', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Engine', models.CharField(max_length=50)),
                ('VIN', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Group', models.CharField(max_length=50)),
                ('Course', models.IntegerField()),
                ('Faculty', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
