# Generated by Django 4.2.1 on 2023-05-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automobiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='Engine',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='Model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='VIN',
            new_name='vin',
        ),
        migrations.RenameField(
            model_name='tableautomobiles',
            old_name='Year',
            new_name='year',
        ),
    ]
