# Generated by Django 4.2.1 on 2023-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_automobiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('engine', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
                ('status', models.CharField(default='Available', max_length=50)),
            ],
        ),
    ]
