
### PRICE BETWEEN 50280 AND 34600

POST http://127.0.0.1:8000/api/data HTTP/1.1
Content-Type: application/json; charset=utf-8
Origin: http://example.com


{
  "filters": [
    {"field": "title",  "operator": "IN",   "value": " джинсы | куртка" },
    {"field": "price",  "operator": "BT",   "value": " 14500 | 22350"   }
  ],
  "limit": 2
}


### PRICE 41250 OR PRICE 3900

POST http://127.0.0.1:8000/api/data HTTP/1.1
Content-Type: application/json; charset=utf-8
Origin: http://example.com


{
  "filters": [
    {"field": "title",  "operator": "IN",   "value": " джинсы | куртка" },
    {"field": "color",  "operator": "IN",   "value": " красный | розовый"  },
    {"field": "price",  "operator": "BT",   "value": " 80600 | 120500"   }
  ],
  "limit": 1
}

























